// pdfReport.js
const PDFDocument = require("pdfkit");
const fs = require("fs");

function generateWaterFootprintPDF(data, res) {
  const doc = new PDFDocument();
  
  // Set the response headers to download
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", "attachment; filename=water-footprint-report.pdf");

  // Pipe PDF to response
  doc.pipe(res);

  // Title
  doc.fontSize(22).text("Water Footprint Report", { align: "center" });
  doc.moveDown();

  // User Inputs Section
  doc.fontSize(16).text("User Inputs", { underline: true });
  doc.moveDown(0.5);

  Object.keys(data.inputs).forEach(key => {
    doc.fontSize(12).text(`${key}: ${data.inputs[key]}`);
  });

  doc.moveDown();

  // Result Section
  doc.fontSize(16).text("Calculated Water Footprint", { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(14).text(`Total Water Footprint: ${data.result} Liters`);

  doc.moveDown();

  // Additional Notes
  doc.fontSize(12).text("This report was auto-generated by the Water Footprint Detection System.");
  
  // Finalize PDF
  doc.end();
}

module.exports = generateWaterFootprintPDF;
